# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0  # LTS
  - 1.3  # Latest release
  - nightly
arch:
  - x64
  - x86
jobs:
  # Test unmaintained releases only on Linux 64-bit
  include:
    - julia: 1.1
      os: linux
    - julia: 1.2
      os: linux
  # Test 32-bit only on Linux
  exclude:
    - arch: x86
      os: osx
    - arch: x86
      os: windows
env:
  - JULIA_PROJECT="@."
git:
  depth: 999999
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
