desc = "Allows Julia function calls to be temporarily overloaded for purpose of testing"
keywords = ["testing", "mocking"]
author = ["Curtis Vogt"]
license = "MIT"
name = "Mocking"
uuid = "78c3b35d-d492-501b-9361-3d52fe80e533"
version = "0.6.0"

[compat]
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test"]
